namespace Allyaria.Theming.Helpers;

/// <summary>
/// Represents a single theming update instruction that pairs a <see cref="ThemeNavigator" /> with a corresponding
/// <see cref="IStyleValue" /> to modify style properties within the Allyaria theming system.
/// </summary>
/// <remarks>
///     <para>
///     Each <see cref="ThemeUpdater" /> defines the mapping between a navigation context (which specifies components,
///     states, and theme types) and a concrete style value to apply.
///     </para>
///     <para>
///     These instances are typically generated by <see cref="ThemeApplierBase" /> and consumed by
///     <see cref="IThemeConfigurator" /> or <see cref="ThemeBuilder" /> during theme composition.
///     </para>
/// </remarks>
/// <param name="Navigator">
/// The <see cref="ThemeNavigator" /> defining the scope of components, states, and styles affected by this update.
/// </param>
/// <param name="Value">
/// The <see cref="IStyleValue" /> representing the CSS or visual style value to apply. May be <see langword="null" /> if
/// the updater is used as a placeholder or mapping definition.
/// </param>
public readonly record struct ThemeUpdater(ThemeNavigator Navigator, IStyleValue? Value);
