namespace Allyaria.Theming.Enumerations;

/// <summary>
/// Represents the available CSS style properties recognized by the Allyaria theming system. Each enumeration value maps to
/// a specific CSS property name used in dynamic style generation.
/// </summary>
public enum StyleType
{
    /// <summary>
    /// The accent-color CSS property sets the accent color for user-interface controls generated by some elements.
    /// </summary>
    [Description(description: "accent-color")]
    AccentColor,

    /// <summary>
    /// The CSS align-content property sets the distribution of space between and around content items along a flexbox's cross
    /// axis, or a grid or block-level element's block axis.
    /// </summary>
    [Description(description: "align-content")]
    AlignContent,

    /// <summary>
    /// The CSS align-items property sets the align-self value on all direct children as a group. In flexbox, it controls the
    /// alignment of items on the cross axis. In grid layout, it controls the alignment of items on the block axis within their
    /// grid areas.
    /// </summary>
    [Description(description: "align-items")]
    AlignItems,

    /// <summary>
    /// The alignment-baseline CSS property specifies the specific baseline used to align the box's text and inline-level
    /// contents. Baseline alignment is the relationship among the baselines of multiple alignment subjects within an alignment
    /// context. When performing baseline alignment, the alignment-baseline property value specifies which baseline of the box
    /// is aligned to the corresponding baseline of its alignment context.
    /// </summary>
    [Description(description: "alignment-baseline")]
    AlignmentBaseline,

    /// <summary>
    /// The align-self CSS property overrides a grid or flex item's align-items value. In grid, it aligns the item inside the
    /// grid area. In flexbox, it aligns the item on the cross axis.
    /// </summary>
    [Description(description: "align-self")]
    AlignSelf,

    /// <summary>The background-color CSS property sets the background color of an element.</summary>
    [Description(description: "background-color")]
    BackgroundColor,

    /// <summary>The border-color shorthand CSS property sets the color of an element's border.</summary>
    [Description(description: "border-color")]
    BorderColor,

    /// <summary>
    /// The border-radius CSS property rounds the corners of an element's outer border edge. You can set a single radius to
    /// make circular corners, or two radii to make elliptical corners.
    /// </summary>
    [Description(description: "border-radius")]
    BorderRadius,

    /// <summary>
    /// The border-style shorthand CSS property sets the line style for all four sides of an element's border.
    /// </summary>
    [Description(description: "border-style")]
    BorderStyle,

    /// <summary>The border-width shorthand CSS property sets the width of an element's border.</summary>
    [Description(description: "border-width")]
    BorderWidth,

    /// <summary>The box-sizing CSS property sets how the total width and height of an element is calculated.</summary>
    [Description(description: "box-sizing")]
    BoxSizing,

    /// <summary>
    /// The caret-color CSS property sets the color of the insertion caret, sometimes referred to as the text input cursor.
    /// This is the visible marker appearing at the insertion point where the next character typed will be added or where the
    /// next character deleted will be removed.
    /// </summary>
    [Description(description: "caret-color")]
    CaretColor,

    /// <summary>
    /// The color CSS property sets the foreground color value of an element's text and text decorations, and sets the
    /// currentColor value. currentColor may be used as an indirect value on other properties and is the default for other
    /// color properties, such as border-color.
    /// </summary>
    [Description(description: "color")]
    Color,

    /// <summary>
    /// The display CSS property sets whether an element is treated as a block or inline box and the layout used for its
    /// children, such as flow layout, grid or flex.
    /// </summary>
    [Description(description: "display")]
    Display,

    /// <summary>
    /// The font-family CSS property specifies a prioritized list of one or more font family names and/or generic family names
    /// for the selected element.
    /// </summary>
    [Description(description: "font-family")]
    FontFamily,

    /// <summary>
    /// The font-size CSS property sets the size of the font. Changing the font size also updates the sizes of the font
    /// size-relative <length> units, such as em, ex, and so forth.
    /// </summary>
    [Description(description: "font-size")]
    FontSize,

    /// <summary>
    /// The font-style CSS property sets whether a font should be styled with a normal, italic, or oblique face from its
    /// font-family.
    /// </summary>
    [Description(description: "font-style")]
    FontStyle,

    /// <summary>
    /// The font-weight CSS property sets the weight (or boldness) of the font. The weights available depend on the font-family
    /// that is currently set.
    /// </summary>
    [Description(description: "font-weight")]
    FontWeight,

    /// <summary>
    /// The height CSS property specifies the height of an element. By default, the property defines the height of the content
    /// area. If box-sizing is set to border-box, however, it instead determines the height of the border area.
    /// </summary>
    [Description(description: "height")]
    Height,

    /// <summary>
    /// The hyphens CSS property specifies how words should be hyphenated when text wraps across multiple lines. It can prevent
    /// hyphenation entirely, hyphenate at manually-specified points within the text, or let the browser automatically insert
    /// hyphens where appropriate.
    /// </summary>
    [Description(description: "hyphens")]
    Hyphens,

    /// <summary>
    /// The CSS justify-content property defines how the browser distributes space between and around content items along the
    /// main axis of a flex container and the inline axis of grid and multicol containers.
    /// </summary>
    [Description(description: "justify-content")]
    JustifyContent,

    /// <summary>
    /// The CSS justify-items property defines the default justify-self for all items of the box, giving them all a default way
    /// of justifying each box along the appropriate axis.
    /// </summary>
    [Description(description: "justify-items")]
    JustifyItems,

    /// <summary>
    /// The CSS justify-self property sets the way a box is justified inside its alignment container along the appropriate
    /// axis.
    /// </summary>
    [Description(description: "justify-self")]
    JustifySelf,

    /// <summary>
    /// The letter-spacing CSS property sets the horizontal spacing behavior between text characters. This value is added to
    /// the natural spacing between characters while rendering the text. Positive values of letter-spacing causes characters to
    /// spread farther apart, while negative values of letter-spacing bring characters closer together.
    /// </summary>
    [Description(description: "letter-spacing")]
    LetterSpacing,

    /// <summary>
    /// The line-break CSS property sets how to break lines of Chinese, Japanese, or Korean (CJK) text when working with
    /// punctuation and symbols.
    /// </summary>
    [Description(description: "line-break")]
    LineBreak,

    /// <summary>
    /// The line-height CSS property sets the height of a line box in horizontal writing modes. In vertical writing modes, it
    /// sets the width of a line box. It's commonly used to set the distance between lines of text. On block-level elements in
    /// horizontal writing modes, it specifies the preferred height of line boxes within the element, and on non-replaced
    /// inline elements, it specifies the height that is used to calculate line box height.
    /// </summary>
    [Description(description: "line-height")]
    LineHeight,

    /// <summary>The margin CSS shorthand property sets the margin area on all four sides of an element.</summary>
    [Description(description: "margin")]
    Margin,

    /// <summary>
    /// The max-height CSS property sets the maximum height of an element. It prevents the used value of the height property
    /// from becoming larger than the value specified for max-height.
    /// </summary>
    [Description(description: "max-height")]
    MaxHeight,

    /// <summary>
    /// The max-width CSS property sets the maximum width of an element. It prevents the used value of the width property from
    /// becoming larger than the value specified by max-width.
    /// </summary>
    [Description(description: "max-width")]
    MaxWidth,

    /// <summary>
    /// The min-height CSS property sets the minimum height of an element. It prevents the used value of the height property
    /// from becoming smaller than the value specified for min-height.
    /// </summary>
    [Description(description: "min-height")]
    MinHeight,

    /// <summary>
    /// The min-width CSS property sets the minimum width of an element. It prevents the used value of the width property from
    /// becoming smaller than the value specified for min-width.
    /// </summary>
    [Description(description: "min-width")]
    MinWidth,

    /// <summary>The outline-color CSS property sets the color of an element's outline.</summary>
    [Description(description: "outline-color")]
    OutlineColor,

    /// <summary>
    /// The outline-offset CSS property sets the amount of space between an outline and the edge or border of an element.
    /// </summary>
    [Description(description: "outline-offset")]
    OutlineOffset,

    /// <summary>
    /// The outline-style CSS property sets the style of an element's outline. An outline is a line that is drawn around an
    /// element, outside the border.
    /// </summary>
    [Description(description: "outline-style")]
    OutlineStyle,

    /// <summary>
    /// The CSS outline-width property sets the thickness of an element's outline. An outline is a line that is drawn around an
    /// element, outside the border.
    /// </summary>
    [Description(description: "outline-width")]
    OutlineWidth,

    /// <summary>
    /// The overflow CSS shorthand property sets the desired behavior when content does not fit in the element's padding box
    /// (overflows) in the horizontal and/or vertical direction.
    /// </summary>
    [Description(description: "overflow")]
    Overflow,

    /// <summary>
    /// The overflow-block CSS property sets what shows when content overflows the block start and block end edges of a box.
    /// This may be nothing, a scroll bar, or the overflow content.
    /// </summary>
    [Description(description: "overflow-block")]
    OverflowBlock,

    /// <summary>
    /// The overflow-inline CSS property sets what shows when content overflows the inline start and end edges of a box. This
    /// may be nothing, a scroll bar, or the overflow content.
    /// </summary>
    [Description(description: "overflow-inline")]
    OverflowInline,

    /// <summary>
    /// The overflow-wrap CSS property applies to text, setting whether the browser should insert line breaks within an
    /// otherwise unbreakable string to prevent text from overflowing its line box.
    /// </summary>
    [Description(description: "overflow-wrap")]
    OverflowWrap,

    /// <summary>
    /// The overscroll-behavior CSS property sets what a browser does when reaching the boundary of a scrolling area.
    /// </summary>
    [Description(description: "overscroll-behavior")]
    OverscrollBehavior,

    /// <summary>
    /// The overscroll-behavior-block CSS property sets the browser's behavior when the block direction boundary of a scrolling
    /// area is reached.
    /// </summary>
    [Description(description: "overscroll-behavior-block")]
    OverscrollBehaviorBlock,

    /// <summary>
    /// The overscroll-behavior-inline CSS property sets the browser's behavior when the inline direction boundary of a
    /// scrolling area is reached.
    /// </summary>
    [Description(description: "overscroll-behavior-inline")]
    OverscrollBehaviorInline,

    /// <summary>The padding CSS shorthand property sets the padding area on all four sides of an element at once.</summary>
    [Description(description: "padding")]
    Padding,

    /// <summary>
    /// The position CSS property sets how an element is positioned in a document. The top, right, bottom, and left physical
    /// properties and the inset-block-start, inset-block-end, inset-inline-start, and inset-inline-end flow-relative logical
    /// properties can be used to determine the final location of positioned elements.
    /// </summary>
    [Description(description: "position")]
    Position,

    /// <summary>
    /// The scroll-behavior CSS property sets the behavior for a scrolling box when scrolling is triggered by the navigation or
    /// CSSOM scrolling APIs.
    /// </summary>
    [Description(description: "scroll-behavior")]
    ScrollBehavior,

    /// <summary>
    /// The text-align CSS property sets the horizontal alignment of the inline-level content inside a block element or
    /// table-cell box. This means it works like vertical-align but in the horizontal direction.
    /// </summary>
    [Description(description: "text-align")]
    TextAlign,

    /// <summary>
    /// The text-decoration-color CSS property sets the color of decorations added to text by text-decoration-line.
    /// </summary>
    [Description(description: "text-decoration-color")]
    TextDecorationColor,

    /// <summary>
    /// The text-decoration-line CSS property sets the kind of decoration that is used on text in an element, such as an
    /// underline or overline.
    /// </summary>
    [Description(description: "text-decoration-line")]
    TextDecorationLine,

    /// <summary>
    /// The text-decoration-style CSS property sets the style of the lines specified by text-decoration-line. The style applies
    /// to all lines that are set with text-decoration-line.
    /// </summary>
    [Description(description: "text-decoration-style")]
    TextDecorationStyle,

    /// <summary>
    /// The text-decoration-thickness CSS property sets the stroke thickness of the decoration line that is used on
    /// text in an element, such as a line-through, underline, or overline./summary>
    [Description(description: "text-decoration-thickness")]
    TextDecorationThickness,

    /// <summary>
    /// The text-indent CSS property sets the length of empty space (indentation) that is put before lines of text in a block.
    /// </summary>
    [Description(description: "text-indent")]
    TextIndent,

    /// <summary>
    /// The text-orientation CSS property sets the orientation of the text characters in a line. It only affects text in
    /// vertical mode (when writing-mode is not horizontal-tb). It is useful for controlling the display of languages that use
    /// vertical script, and also for making vertical table headers.
    /// </summary>
    [Description(description: "text-orientation")]
    TextOrientation,

    /// <summary>
    /// The text-overflow CSS property sets how hidden overflow content is signaled to users. It can be clipped, display an
    /// ellipsis (…), or display a custom string.
    /// </summary>
    [Description(description: "text-overflow")]
    TextOverflow,

    /// <summary>Specifies how font sizes should be adjusted for display devices.</summary>
    [Description(description: "text-size-adjust")]
    TextSizeAdjust,

    /// <summary>
    /// The text-transform CSS property specifies how to capitalize an element's text. It can be used to make text appear in
    /// all-uppercase or all-lowercase, or with each word capitalized. It also can help improve legibility for ruby.
    /// </summary>
    [Description(description: "text-transform")]
    TextTransform,

    /// <summary>
    /// The text-underline-offset CSS property sets the offset distance of an underline text decoration line (applied using
    /// text-decoration) from its original position.
    /// </summary>
    [Description(description: "text-underline-offset")]
    TextUnderlineOffset,

    /// <summary>
    /// The text-wrap-style CSS property controls how text inside an element is wrapped. The different values provide alternate
    /// ways of wrapping the content of a block element.
    /// </summary>
    [Description(description: "text-wrap-style")]
    TextWrapStyle,

    /// <summary>
    /// The vertical-align CSS property sets vertical alignment of an inline, inline-block or table-cell box.
    /// </summary>
    [Description(description: "vertical-align")]
    VerticalAlign,

    /// <summary>The white-space CSS property sets how white space inside an element is handled.</summary>
    [Description(description: "white-space")]
    WhiteSpace,

    /// <summary>
    /// The width CSS property sets an element's width. By default, it sets the width of the content area, but if box-sizing is
    /// set to border-box, it sets the width of the border area.
    /// </summary>
    [Description(description: "width")]
    Width,

    /// <summary>
    /// The word-break CSS property sets whether line breaks appear wherever the text would otherwise overflow its content box.
    /// </summary>
    [Description(description: "word-break")]
    WordBreak,

    /// <summary>The word-spacing CSS property sets the length of space between words and between tags.</summary>
    [Description(description: "word-spacing")]
    WordSpacing,

    /// <summary>
    /// The writing-mode CSS property sets whether lines of text are laid out horizontally or vertically, as well as the
    /// direction in which blocks progress. When set for an entire document, it should be set on the root element (html element
    /// for HTML documents).
    /// </summary>
    [Description(description: "writing-mode")]
    WritingMode,

    /// <summary>
    /// The z-index CSS property sets the z-order of a positioned element and its descendants or flex and grid items.
    /// Overlapping elements with a larger z-index cover those with a smaller one.
    /// </summary>
    [Description(description: "z-index")]
    ZIndex,

    /// <summary>
    /// The zoom CSS property can be used to control the magnification level of an element. The zoom CSS property scales the
    /// targeted element, which can affect the page layout. When scaling, the zoomed element scales from top and center when
    /// using the default writing-mode.
    /// </summary>
    [Description(description: "zoom")]
    Zoom
}
