using System.Text.RegularExpressions;

namespace Allyaria.Theming.Styles;

public readonly partial struct AllyariaColor
{
    /// <summary>Material Design color lookup table.</summary>
    private static readonly Dictionary<string, AllyariaColor> MaterialMap = new(StringComparer.OrdinalIgnoreCase)
    {
        // Red
        ["red50"] = FromHexInline("#FFEBEEFF"),
        ["red100"] = FromHexInline("#FFCDD2FF"),
        ["red200"] = FromHexInline("#EF9A9AFF"),
        ["red300"] = FromHexInline("#E57373FF"),
        ["red400"] = FromHexInline("#EF5350FF"),
        ["red500"] = FromHexInline("#F44336FF"),
        ["red600"] = FromHexInline("#E53935FF"),
        ["red700"] = FromHexInline("#D32F2FFF"),
        ["red800"] = FromHexInline("#C62828FF"),
        ["red900"] = FromHexInline("#B71C1CFF"),
        ["reda100"] = FromHexInline("#FF8A80FF"),
        ["reda200"] = FromHexInline("#FF5252FF"),
        ["reda400"] = FromHexInline("#FF1744FF"),
        ["reda700"] = FromHexInline("#D50000FF"),

        // Pink
        ["pink50"] = FromHexInline("#FCE4ECFF"),
        ["pink100"] = FromHexInline("#F8BBD0FF"),
        ["pink200"] = FromHexInline("#F48FB1FF"),
        ["pink300"] = FromHexInline("#F06292FF"),
        ["pink400"] = FromHexInline("#EC407AFF"),
        ["pink500"] = FromHexInline("#E91E63FF"),
        ["pink600"] = FromHexInline("#D81B60FF"),
        ["pink700"] = FromHexInline("#C2185BFF"),
        ["pink800"] = FromHexInline("#AD1457FF"),
        ["pink900"] = FromHexInline("#880E4FFF"),
        ["pinka100"] = FromHexInline("#FF80ABFF"),
        ["pinka200"] = FromHexInline("#FF4081FF"),
        ["pinka400"] = FromHexInline("#F50057FF"),
        ["pinka700"] = FromHexInline("#C51162FF"),

        // Purple
        ["purple50"] = FromHexInline("#F3E5F5FF"),
        ["purple100"] = FromHexInline("#E1BEE7FF"),
        ["purple200"] = FromHexInline("#CE93D8FF"),
        ["purple300"] = FromHexInline("#BA68C8FF"),
        ["purple400"] = FromHexInline("#AB47BCFF"),
        ["purple500"] = FromHexInline("#9C27B0FF"),
        ["purple600"] = FromHexInline("#8E24AAFF"),
        ["purple700"] = FromHexInline("#7B1FA2FF"),
        ["purple800"] = FromHexInline("#6A1B9AFF"),
        ["purple900"] = FromHexInline("#4A148CFF"),
        ["purplea100"] = FromHexInline("#EA80FCFF"),
        ["purplea200"] = FromHexInline("#E040FBFF"),
        ["purplea400"] = FromHexInline("#D500F9FF"),
        ["purplea700"] = FromHexInline("#AA00FFFF"),

        // Deep Purple
        ["deeppurple50"] = FromHexInline("#EDE7F6FF"),
        ["deeppurple100"] = FromHexInline("#D1C4E9FF"),
        ["deeppurple200"] = FromHexInline("#B39DDBFF"),
        ["deeppurple300"] = FromHexInline("#9575CDFF"),
        ["deeppurple400"] = FromHexInline("#7E57C2FF"),
        ["deeppurple500"] = FromHexInline("#673AB7FF"),
        ["deeppurple600"] = FromHexInline("#5E35B1FF"),
        ["deeppurple700"] = FromHexInline("#512DA8FF"),
        ["deeppurple800"] = FromHexInline("#4527A0FF"),
        ["deeppurple900"] = FromHexInline("#311B92FF"),
        ["deeppurplea100"] = FromHexInline("#B388FFFF"),
        ["deeppurplea200"] = FromHexInline("#7C4DFFFF"),
        ["deeppurplea400"] = FromHexInline("#651FFFFF"),
        ["deeppurplea700"] = FromHexInline("#6200EAFF"),

        // Indigo
        ["indigo50"] = FromHexInline("#E8EAF6FF"),
        ["indigo100"] = FromHexInline("#C5CAE9FF"),
        ["indigo200"] = FromHexInline("#9FA8DAFF"),
        ["indigo300"] = FromHexInline("#7986CBFF"),
        ["indigo400"] = FromHexInline("#5C6BC0FF"),
        ["indigo500"] = FromHexInline("#3F51B5FF"),
        ["indigo600"] = FromHexInline("#3949ABFF"),
        ["indigo700"] = FromHexInline("#303F9FFF"),
        ["indigo800"] = FromHexInline("#283593FF"),
        ["indigo900"] = FromHexInline("#1A237EFF"),
        ["indigoa100"] = FromHexInline("#8C9EFFFF"),
        ["indigoa200"] = FromHexInline("#536DFEFF"),
        ["indigoa400"] = FromHexInline("#3D5AFEFF"),
        ["indigoa700"] = FromHexInline("#304FFEFF"),

        // Blue
        ["blue50"] = FromHexInline("#E3F2FDFF"),
        ["blue100"] = FromHexInline("#BBDEFBFF"),
        ["blue200"] = FromHexInline("#90CAF9FF"),
        ["blue300"] = FromHexInline("#64B5F6FF"),
        ["blue400"] = FromHexInline("#42A5F5FF"),
        ["blue500"] = FromHexInline("#2196F3FF"),
        ["blue600"] = FromHexInline("#1E88E5FF"),
        ["blue700"] = FromHexInline("#1976D2FF"),
        ["blue800"] = FromHexInline("#1565C0FF"),
        ["blue900"] = FromHexInline("#0D47A1FF"),
        ["bluea100"] = FromHexInline("#82B1FFFF"),
        ["bluea200"] = FromHexInline("#448AFFFF"),
        ["bluea400"] = FromHexInline("#2979FFFF"),
        ["bluea700"] = FromHexInline("#2962FFFF"),

        // Light Blue
        ["lightblue50"] = FromHexInline("#E1F5FEFF"),
        ["lightblue100"] = FromHexInline("#B3E5FCFF"),
        ["lightblue200"] = FromHexInline("#81D4FAFF"),
        ["lightblue300"] = FromHexInline("#4FC3F7FF"),
        ["lightblue400"] = FromHexInline("#29B6F6FF"),
        ["lightblue500"] = FromHexInline("#03A9F4FF"),
        ["lightblue600"] = FromHexInline("#039BE5FF"),
        ["lightblue700"] = FromHexInline("#0288D1FF"),
        ["lightblue800"] = FromHexInline("#0277BDFF"),
        ["lightblue900"] = FromHexInline("#01579BFF"),
        ["lightbluea100"] = FromHexInline("#80D8FFFF"),
        ["lightbluea200"] = FromHexInline("#40C4FFFF"),
        ["lightbluea400"] = FromHexInline("#00B0FFFF"),
        ["lightbluea700"] = FromHexInline("#0091EAFF"),

        // Cyan
        ["cyan50"] = FromHexInline("#E0F7FAFF"),
        ["cyan100"] = FromHexInline("#B2EBF2FF"),
        ["cyan200"] = FromHexInline("#80DEEAFF"),
        ["cyan300"] = FromHexInline("#4DD0E1FF"),
        ["cyan400"] = FromHexInline("#26C6DAFF"),
        ["cyan500"] = FromHexInline("#00BCD4FF"),
        ["cyan600"] = FromHexInline("#00ACC1FF"),
        ["cyan700"] = FromHexInline("#0097A7FF"),
        ["cyan800"] = FromHexInline("#00838FFF"),
        ["cyan900"] = FromHexInline("#006064FF"),
        ["cyana100"] = FromHexInline("#84FFFFFF"),
        ["cyana200"] = FromHexInline("#18FFFFFF"),
        ["cyana400"] = FromHexInline("#00E5FFFF"),
        ["cyana700"] = FromHexInline("#00B8D4FF"),

        // Teal
        ["teal50"] = FromHexInline("#E0F2F1FF"),
        ["teal100"] = FromHexInline("#B2DFDBFF"),
        ["teal200"] = FromHexInline("#80CBC4FF"),
        ["teal300"] = FromHexInline("#4DB6ACFF"),
        ["teal400"] = FromHexInline("#26A69AFF"),
        ["teal500"] = FromHexInline("#009688FF"),
        ["teal600"] = FromHexInline("#00897BFF"),
        ["teal700"] = FromHexInline("#00796BFF"),
        ["teal800"] = FromHexInline("#00695CFF"),
        ["teal900"] = FromHexInline("#004D40FF"),
        ["teala100"] = FromHexInline("#A7FFEBFF"),
        ["teala200"] = FromHexInline("#64FFDAFF"),
        ["teala400"] = FromHexInline("#1DE9B6FF"),
        ["teala700"] = FromHexInline("#00BFA5FF"),

        // Green
        ["green50"] = FromHexInline("#E8F5E9FF"),
        ["green100"] = FromHexInline("#C8E6C9FF"),
        ["green200"] = FromHexInline("#A5D6A7FF"),
        ["green300"] = FromHexInline("#81C784FF"),
        ["green400"] = FromHexInline("#66BB6AFF"),
        ["green500"] = FromHexInline("#4CAF50FF"),
        ["green600"] = FromHexInline("#43A047FF"),
        ["green700"] = FromHexInline("#388E3CFF"),
        ["green800"] = FromHexInline("#2E7D32FF"),
        ["green900"] = FromHexInline("#1B5E20FF"),
        ["greena100"] = FromHexInline("#B9F6CAFF"),
        ["greena200"] = FromHexInline("#69F0AEFF"),
        ["greena400"] = FromHexInline("#00E676FF"),
        ["greena700"] = FromHexInline("#00C853FF"),

        // Light Green
        ["lightgreen50"] = FromHexInline("#F1F8E9FF"),
        ["lightgreen100"] = FromHexInline("#DCEDC8FF"),
        ["lightgreen200"] = FromHexInline("#C5E1A5FF"),
        ["lightgreen300"] = FromHexInline("#AED581FF"),
        ["lightgreen400"] = FromHexInline("#9CCC65FF"),
        ["lightgreen500"] = FromHexInline("#8BC34AFF"),
        ["lightgreen600"] = FromHexInline("#7CB342FF"),
        ["lightgreen700"] = FromHexInline("#689F38FF"),
        ["lightgreen800"] = FromHexInline("#558B2FFF"),
        ["lightgreen900"] = FromHexInline("#33691EFF"),
        ["lightgreena100"] = FromHexInline("#CCFF90FF"),
        ["lightgreena200"] = FromHexInline("#B2FF59FF"),
        ["lightgreena400"] = FromHexInline("#76FF03FF"),
        ["lightgreena700"] = FromHexInline("#64DD17FF"),

        // Lime
        ["lime50"] = FromHexInline("#F9FBE7FF"),
        ["lime100"] = FromHexInline("#F0F4C3FF"),
        ["lime200"] = FromHexInline("#E6EE9CFF"),
        ["lime300"] = FromHexInline("#DCE775FF"),
        ["lime400"] = FromHexInline("#D4E157FF"),
        ["lime500"] = FromHexInline("#CDDC39FF"),
        ["lime600"] = FromHexInline("#C0CA33FF"),
        ["lime700"] = FromHexInline("#AFB42BFF"),
        ["lime800"] = FromHexInline("#9E9D24FF"),
        ["lime900"] = FromHexInline("#827717FF"),
        ["limea100"] = FromHexInline("#F4FF81FF"),
        ["limea200"] = FromHexInline("#EEFF41FF"),
        ["limea400"] = FromHexInline("#C6FF00FF"),
        ["limea700"] = FromHexInline("#AEEA00FF"),

        // Yellow
        ["yellow50"] = FromHexInline("#FFFDE7FF"),
        ["yellow100"] = FromHexInline("#FFF9C4FF"),
        ["yellow200"] = FromHexInline("#FFF59DFF"),
        ["yellow300"] = FromHexInline("#FFF176FF"),
        ["yellow400"] = FromHexInline("#FFEE58FF"),
        ["yellow500"] = FromHexInline("#FFEB3BFF"),
        ["yellow600"] = FromHexInline("#FDD835FF"),
        ["yellow700"] = FromHexInline("#FBC02DFF"),
        ["yellow800"] = FromHexInline("#F9A825FF"),
        ["yellow900"] = FromHexInline("#F57F17FF"),
        ["yellowa100"] = FromHexInline("#FFFF8DFF"),
        ["yellowa200"] = FromHexInline("#FFFF00FF"),
        ["yellowa400"] = FromHexInline("#FFEA00FF"),
        ["yellowa700"] = FromHexInline("#FFD600FF"),

        // Amber
        ["amber50"] = FromHexInline("#FFF8E1FF"),
        ["amber100"] = FromHexInline("#FFECB3FF"),
        ["amber200"] = FromHexInline("#FFE082FF"),
        ["amber300"] = FromHexInline("#FFD54FFF"),
        ["amber400"] = FromHexInline("#FFCA28FF"),
        ["amber500"] = FromHexInline("#FFC107FF"),
        ["amber600"] = FromHexInline("#FFB300FF"),
        ["amber700"] = FromHexInline("#FFA000FF"),
        ["amber800"] = FromHexInline("#FF8F00FF"),
        ["amber900"] = FromHexInline("#FF6F00FF"),
        ["ambera100"] = FromHexInline("#FFE57FFF"),
        ["ambera200"] = FromHexInline("#FFD740FF"),
        ["ambera400"] = FromHexInline("#FFC400FF"),
        ["ambera700"] = FromHexInline("#FFAB00FF"),

        // Orange
        ["orange50"] = FromHexInline("#FFF3E0FF"),
        ["orange100"] = FromHexInline("#FFE0B2FF"),
        ["orange200"] = FromHexInline("#FFCC80FF"),
        ["orange300"] = FromHexInline("#FFB74DFF"),
        ["orange400"] = FromHexInline("#FFA726FF"),
        ["orange500"] = FromHexInline("#FF9800FF"),
        ["orange600"] = FromHexInline("#FB8C00FF"),
        ["orange700"] = FromHexInline("#F57C00FF"),
        ["orange800"] = FromHexInline("#EF6C00FF"),
        ["orange900"] = FromHexInline("#E65100FF"),
        ["orangea100"] = FromHexInline("#FFD180FF"),
        ["orangea200"] = FromHexInline("#FFAB40FF"),
        ["orangea400"] = FromHexInline("#FF9100FF"),
        ["orangea700"] = FromHexInline("#FF6D00FF"),

        // Deep Orange
        ["deeporange50"] = FromHexInline("#FBE9E7FF"),
        ["deeporange100"] = FromHexInline("#FFCCBCFF"),
        ["deeporange200"] = FromHexInline("#FFAB91FF"),
        ["deeporange300"] = FromHexInline("#FF8A65FF"),
        ["deeporange400"] = FromHexInline("#FF7043FF"),
        ["deeporange500"] = FromHexInline("#FF5722FF"),
        ["deeporange600"] = FromHexInline("#F4511EFF"),
        ["deeporange700"] = FromHexInline("#E64A19FF"),
        ["deeporange800"] = FromHexInline("#D84315FF"),
        ["deeporange900"] = FromHexInline("#BF360CFF"),
        ["deeporangea100"] = FromHexInline("#FF9E80FF"),
        ["deeporangea200"] = FromHexInline("#FF6E40FF"),
        ["deeporangea400"] = FromHexInline("#FF3D00FF"),
        ["deeporangea700"] = FromHexInline("#DD2C00FF"),

        // Brown (no accents in Material 2 palette)
        ["brown50"] = FromHexInline("#EFEBE9FF"),
        ["brown100"] = FromHexInline("#D7CCC8FF"),
        ["brown200"] = FromHexInline("#BCAAA4FF"),
        ["brown300"] = FromHexInline("#A1887FFF"),
        ["brown400"] = FromHexInline("#8D6E63FF"),
        ["brown500"] = FromHexInline("#795548FF"),
        ["brown600"] = FromHexInline("#6D4C41FF"),
        ["brown700"] = FromHexInline("#5D4037FF"),
        ["brown800"] = FromHexInline("#4E342EFF"),
        ["brown900"] = FromHexInline("#3E2723FF"),

        // Blue Grey (no accents)
        ["bluegrey50"] = FromHexInline("#ECEFF1FF"),
        ["bluegrey100"] = FromHexInline("#CFD8DCFF"),
        ["bluegrey200"] = FromHexInline("#B0BEC5FF"),
        ["bluegrey300"] = FromHexInline("#90A4AEFF"),
        ["bluegrey400"] = FromHexInline("#78909CFF"),
        ["bluegrey500"] = FromHexInline("#607D8BFF"),
        ["bluegrey600"] = FromHexInline("#546E7AFF"),
        ["bluegrey700"] = FromHexInline("#455A64FF"),
        ["bluegrey800"] = FromHexInline("#37474FFF"),
        ["bluegrey900"] = FromHexInline("#263238FF"),

        // Grey (no accents)
        ["grey50"] = FromHexInline("#FAFAFAFF"),
        ["grey100"] = FromHexInline("#F5F5F5FF"),
        ["grey200"] = FromHexInline("#EEEEEEFF"),
        ["grey300"] = FromHexInline("#E0E0E0FF"),
        ["grey400"] = FromHexInline("#BDBDBDFF"),
        ["grey500"] = FromHexInline("#9E9E9EFF"),
        ["grey600"] = FromHexInline("#757575FF"),
        ["grey700"] = FromHexInline("#616161FF"),
        ["grey800"] = FromHexInline("#424242FF"),
        ["grey900"] = FromHexInline("#212121FF"),

        // Monochrome convenience entries
        ["black"] = FromHexInline("#000000FF"),
        ["white"] = FromHexInline("#FFFFFFFF")
    };

    /// <summary>Compiled regular expression for parsing CSS <c>hsv()</c> and <c>hsva()</c> functions.</summary>
    private static readonly Regex RxHsv = new(
        @"^hsva?\s*\(\s*(?<h>(\d*\.)?\d+)\s*,\s*(?<s>(\d*\.)?\d+)\s*%\s*,\s*(?<v>(\d*\.)?\d+)\s*%(?:\s*,\s*(?<a>((\d*\.)?\d+)))?\s*\)\s*$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase
    );

    /// <summary>Compiled regular expression for parsing CSS <c>rgb()</c> and <c>rgba()</c> functions.</summary>
    private static readonly Regex RxRgb = new(
        @"^rgba?\s*\(\s*(?<r>\d{1,3})\s*,\s*(?<g>\d{1,3})\s*,\s*(?<b>\d{1,3})(?:\s*,\s*(?<a>((\d*\.)?\d+)))?\s*\)\s*$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase
    );

    /// <summary>CSS Web color lookup table.</summary>
    private static readonly Dictionary<string, AllyariaColor> WebNameMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["aliceblue"] = FromHexInline("#F0F8FFFF"),
        ["antiquewhite"] = FromHexInline("#FAEBD7FF"),
        ["aqua"] = FromHexInline("#00FFFFFF"),
        ["aquamarine"] = FromHexInline("#7FFFD4FF"),
        ["azure"] = FromHexInline("#F0FFFFFF"),
        ["beige"] = FromHexInline("#F5F5DCFF"),
        ["bisque"] = FromHexInline("#FFE4C4FF"),
        ["black"] = FromHexInline("#000000FF"),
        ["blanchedalmond"] = FromHexInline("#FFEBCDFF"),
        ["blue"] = FromHexInline("#0000FFFF"),
        ["blueviolet"] = FromHexInline("#8A2BE2FF"),
        ["brown"] = FromHexInline("#A52A2AFF"),
        ["burlywood"] = FromHexInline("#DEB887FF"),
        ["cadetblue"] = FromHexInline("#5F9EA0FF"),
        ["chartreuse"] = FromHexInline("#7FFF00FF"),
        ["chocolate"] = FromHexInline("#D2691EFF"),
        ["coral"] = FromHexInline("#FF7F50FF"),
        ["cornflowerblue"] = FromHexInline("#6495EDFF"),
        ["cornsilk"] = FromHexInline("#FFF8DCFF"),
        ["crimson"] = FromHexInline("#DC143CFF"),
        ["cyan"] = FromHexInline("#00FFFFFF"),
        ["darkblue"] = FromHexInline("#00008BFF"),
        ["darkcyan"] = FromHexInline("#008B8BFF"),
        ["darkgoldenrod"] = FromHexInline("#B8860BFF"),
        ["darkgray"] = FromHexInline("#A9A9A9FF"),
        ["darkgreen"] = FromHexInline("#006400FF"),
        ["darkkhaki"] = FromHexInline("#BDB76BFF"),
        ["darkmagenta"] = FromHexInline("#8B008BFF"),
        ["darkolivegreen"] = FromHexInline("#556B2FFF"),
        ["darkorange"] = FromHexInline("#FF8C00FF"),
        ["darkorchid"] = FromHexInline("#9932CCFF"),
        ["darkred"] = FromHexInline("#8B0000FF"),
        ["darksalmon"] = FromHexInline("#E9967AFF"),
        ["darkseagreen"] = FromHexInline("#8FBC8FFF"),
        ["darkslateblue"] = FromHexInline("#483D8BFF"),
        ["darkslategray"] = FromHexInline("#2F4F4FFF"),
        ["darkturquoise"] = FromHexInline("#00CED1FF"),
        ["darkviolet"] = FromHexInline("#9400D3FF"),
        ["deeppink"] = FromHexInline("#FF1493FF"),
        ["deepskyblue"] = FromHexInline("#00BFFFFF"),
        ["dimgray"] = FromHexInline("#696969FF"),
        ["dodgerblue"] = FromHexInline("#1E90FFFF"),
        ["firebrick"] = FromHexInline("#B22222FF"),
        ["floralwhite"] = FromHexInline("#FFFAF0FF"),
        ["forestgreen"] = FromHexInline("#228B22FF"),
        ["fuchsia"] = FromHexInline("#FF00FFFF"),
        ["gainsboro"] = FromHexInline("#DCDCDCFF"),
        ["ghostwhite"] = FromHexInline("#F8F8FFFF"),
        ["gold"] = FromHexInline("#FFD700FF"),
        ["goldenrod"] = FromHexInline("#DAA520FF"),
        ["gray"] = FromHexInline("#808080FF"),
        ["green"] = FromHexInline("#008000FF"),
        ["greenyellow"] = FromHexInline("#ADFF2FFF"),
        ["honeydew"] = FromHexInline("#F0FFF0FF"),
        ["hotpink"] = FromHexInline("#FF69B4FF"),
        ["indianred"] = FromHexInline("#CD5C5CFF"),
        ["indigo"] = FromHexInline("#4B0082FF"),
        ["ivory"] = FromHexInline("#FFFFF0FF"),
        ["khaki"] = FromHexInline("#F0E68CFF"),
        ["lavender"] = FromHexInline("#E6E6FAFF"),
        ["lavenderblush"] = FromHexInline("#FFF0F5FF"),
        ["lawngreen"] = FromHexInline("#7CFC00FF"),
        ["lemonchiffon"] = FromHexInline("#FFFACDFF"),
        ["lightblue"] = FromHexInline("#ADD8E6FF"),
        ["lightcoral"] = FromHexInline("#F08080FF"),
        ["lightcyan"] = FromHexInline("#E0FFFFFF"),
        ["lightgoldenrodyellow"] = FromHexInline("#FAFAD2FF"),
        ["lightgray"] = FromHexInline("#D3D3D3FF"),
        ["lightgreen"] = FromHexInline("#90EE90FF"),
        ["lightpink"] = FromHexInline("#FFB6C1FF"),
        ["lightsalmon"] = FromHexInline("#FFA07AFF"),
        ["lightseagreen"] = FromHexInline("#20B2AAFF"),
        ["lightskyblue"] = FromHexInline("#87CEFAFF"),
        ["lightslategray"] = FromHexInline("#778899FF"),
        ["lightsteelblue"] = FromHexInline("#B0C4DEFF"),
        ["lightyellow"] = FromHexInline("#FFFFE0FF"),
        ["lime"] = FromHexInline("#00FF00FF"),
        ["limegreen"] = FromHexInline("#32CD32FF"),
        ["linen"] = FromHexInline("#FAF0E6FF"),
        ["magenta"] = FromHexInline("#FF00FFFF"),
        ["maroon"] = FromHexInline("#800000FF"),
        ["mediumaquamarine"] = FromHexInline("#66CDAAFF"),
        ["mediumblue"] = FromHexInline("#0000CDFF"),
        ["mediumorchid"] = FromHexInline("#BA55D3FF"),
        ["mediumpurple"] = FromHexInline("#9370DBFF"),
        ["mediumseagreen"] = FromHexInline("#3CB371FF"),
        ["mediumslateblue"] = FromHexInline("#7B68EEFF"),
        ["mediumspringgreen"] = FromHexInline("#00FA9AFF"),
        ["mediumturquoise"] = FromHexInline("#48D1CCFF"),
        ["mediumvioletred"] = FromHexInline("#C71585FF"),
        ["midnightblue"] = FromHexInline("#191970FF"),
        ["mintcream"] = FromHexInline("#F5FFFAFF"),
        ["mistyrose"] = FromHexInline("#FFE4E1FF"),
        ["moccasin"] = FromHexInline("#FFE4B5FF"),
        ["navajowhite"] = FromHexInline("#FFDEADFF"),
        ["navy"] = FromHexInline("#000080FF"),
        ["oldlace"] = FromHexInline("#FDF5E6FF"),
        ["olive"] = FromHexInline("#808000FF"),
        ["olivedrab"] = FromHexInline("#6B8E23FF"),
        ["orange"] = FromHexInline("#FFA500FF"),
        ["orangered"] = FromHexInline("#FF4500FF"),
        ["orchid"] = FromHexInline("#DA70D6FF"),
        ["palegoldenrod"] = FromHexInline("#EEE8AAFF"),
        ["palegreen"] = FromHexInline("#98FB98FF"),
        ["paleturquoise"] = FromHexInline("#AFEEEEFF"),
        ["palevioletred"] = FromHexInline("#DB7093FF"),
        ["papayawhip"] = FromHexInline("#FFEFD5FF"),
        ["peachpuff"] = FromHexInline("#FFDAB9FF"),
        ["peru"] = FromHexInline("#CD853FFF"),
        ["pink"] = FromHexInline("#FFC0CBFF"),
        ["plum"] = FromHexInline("#DDA0DDFF"),
        ["powderblue"] = FromHexInline("#B0E0E6FF"),
        ["purple"] = FromHexInline("#800080FF"),
        ["red"] = FromHexInline("#FF0000FF"),
        ["rosybrown"] = FromHexInline("#BC8F8FFF"),
        ["royalblue"] = FromHexInline("#4169E1FF"),
        ["saddlebrown"] = FromHexInline("#8B4513FF"),
        ["salmon"] = FromHexInline("#FA8072FF"),
        ["sandybrown"] = FromHexInline("#F4A460FF"),
        ["seagreen"] = FromHexInline("#2E8B57FF"),
        ["seashell"] = FromHexInline("#FFF5EEFF"),
        ["sienna"] = FromHexInline("#A0522DFF"),
        ["silver"] = FromHexInline("#C0C0C0FF"),
        ["skyblue"] = FromHexInline("#87CEEBFF"),
        ["slateblue"] = FromHexInline("#6A5ACDFF"),
        ["slategray"] = FromHexInline("#708090FF"),
        ["snow"] = FromHexInline("#FFFAFAFF"),
        ["springgreen"] = FromHexInline("#00FF7FFF"),
        ["steelblue"] = FromHexInline("#4682B4FF"),
        ["tan"] = FromHexInline("#D2B48CFF"),
        ["teal"] = FromHexInline("#008080FF"),
        ["thistle"] = FromHexInline("#D8BFD8FF"),
        ["tomato"] = FromHexInline("#FF6347FF"),
        ["turquoise"] = FromHexInline("#40E0D0FF"),
        ["violet"] = FromHexInline("#EE82EEFF"),
        ["wheat"] = FromHexInline("#F5DEB3FF"),
        ["white"] = FromHexInline("#FFFFFFFF"),
        ["whitesmoke"] = FromHexInline("#F5F5F5FF"),
        ["yellow"] = FromHexInline("#FFFF00FF"),
        ["yellowgreen"] = FromHexInline("#9ACD32FF"),
        ["transparent"] = new AllyariaColor(0, 0, 0, 0)
    };
}
