name: Tests & Coverage

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write          # for PR test results publishing
  pull-requests: write   # for PR annotations/comments

jobs:
  test:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # ---- OPTION B (recommended): built-in collector (no NuGet needed)
      - name: Test with coverage (XPlat collector)
        run: |
          set -e
          dotnet test --no-build --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --collect:"XPlat Code Coverage"

          echo "---- locate cobertura files (debug) ----"
          find "$(pwd)" -type f -name "coverage.cobertura.xml" -print || true

      # Publish TRX into PR as a check (disabled for forked PRs)
      - name: Publish unit test results to PR
        if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork && always() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/test-results.trx
            **/TestResults/**/*.trx

      # Generate HTML coverage + badges, and enforce 75% line coverage threshold
      - name: Generate coverage HTML, badges, and enforce threshold
        if: ${{ always() }}
        run: |
          set -e
          dotnet tool update -g dotnet-reportgenerator-globaltool
          export PATH="$PATH:/github/home/.dotnet/tools"

          # XPlat collector writes per-test-project under TestResults/**/coverage.cobertura.xml
          SRC="**/TestResults/**/coverage.cobertura.xml"
          echo "Using reports pattern: $SRC"

          if ! compgen -G "$SRC" > /dev/null; then
            echo "No coverage files found from XPlat collector."
            mkdir -p coverage-report
            printf '%s\n' \
              '<!doctype html><meta charset="utf-8">' \
              '<title>Coverage</title>' \
              '<h1>No coverage files found for this run.</h1>' \
              '<p>Ensure tests executed and the XPlat collector is enabled.</p>' \
              > coverage-report/index.html
          else
            reportgenerator \
              -reports:"$SRC" \
              -targetdir:"coverage-report" \
              -reporttypes:"Html;HtmlSummary;MarkdownSummaryGithub;Badges;TextSummary"

            echo "---- coverage-report contents ----"
            ls -la coverage-report || true

            # Enforce 75% line coverage using TextSummary output
            # The line 'Line coverage: 83.4%' appears in Summary.txt
            COV_LINE=$(grep -Eo 'Line coverage: *[0-9]+(\.[0-9]+)?%' coverage-report/Summary.txt | grep -Eo '[0-9]+(\.[0-9]+)?')
            if [ -z "$COV_LINE" ]; then
              echo "Could not parse line coverage from Summary.txt"; COV_LINE=0
            fi
            echo "Parsed line coverage: ${COV_LINE}%"
            awk -v cov="$COV_LINE" 'BEGIN { if (cov+0 < 75) { exit 1 } }' || {
              echo "Line coverage ${COV_LINE}% is below required threshold (75%)."
              exit 1
            }
          fi

      # Upload artifacts so you can inspect from the Actions UI
      - name: Upload artifacts (TRX + coverage HTML)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-artifacts
          path: |
            **/TestResults/**/*.trx
            coverage-report/**

      # Add a short coverage summary to the job/PR summary
      - name: Add coverage summary to PR
        if: ${{ always() }}
        run: |
          if [ -f "coverage-report/SummaryGithub.md" ]; then
            echo "## Code Coverage" >> "$GITHUB_STEP_SUMMARY"
            cat coverage-report/SummaryGithub.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No coverage report generated._" >> "$GITHUB_STEP_SUMMARY"
          fi

      # Prepare Pages site (defensive: always produces an index; exclude ./site when copying TRX)
      - name: Prepare site for Pages
        if: ${{ always() }}
        run: |
          set -e
          rm -rf site
          mkdir -p site

          if [ -d "coverage-report" ] && [ "$(ls -A coverage-report)" ]; then
            cp -r coverage-report/* site/ || true
          fi

          mkdir -p site/tests
          # Copy TRX files but exclude the ./site folder to avoid copying onto itself
          find . -path ./site -prune -o -type f -name '*.trx' -print -exec cp {} site/tests/ \; || true

          # Ensure an index exists even if coverage wasn't produced
          if [ ! -f site/index.html ]; then
            printf '%s\n' \
              '<!doctype html><meta charset="utf-8">' \
              '<title>Test & Coverage Reports</title>' \
              '<h1>Test & Coverage Reports</h1>' \
              '<p>No coverage site for this run. TRX files are under <a href="./tests/">/tests/</a>.</p>' \
              > site/index.html
          fi

      # Pages deploy only from main
      - name: Configure Pages
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        uses: actions/configure-pages@v5

      - name: Upload site artifact for Pages
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        uses: actions/deploy-pages@v4
